 name: Run chart-releaser
  uses: helm/chart-releaser-action@v1.6.0
  with:
    charts_dir: charts
    config: cr.yaml
  env:
    CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 name: Run helm-push
  uses: bsord/helm-push@v4.1.0
  with:
    chart-folder: chart
  env:
    username: "${{ secrets.GITHUB_TOKEN }}"
    password: ${{ secrets.HARBOR_PASSWORD }}
    registry-url: ${HARBOR_REGISTRY_URL}
